# Generated by Django 4.2 on 2023-05-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary/images/'),
        ),
    ]
